# codecov.yml

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

# src/prior builds are one offs, but we could support them someday
ignore:
  - "src/prior_build"