## This script builds the skyLines priors from a bunch of samples generated by sample_sky.jl
# E5: reads the sampler's HDF5 outputs (skyline_NNN.h5, skymsk_NNN.h5, skyivar_NNN.h5)
# from a --sample_dir argument (or ENV["SKY_SAMPLE_DIR"]); the .jdat/hardcoded-date-path
# era is gone, and the never-produced skyvar_* VARIANCE files are replaced by the
# sampler's skyivar_* INVERSE-variance files used directly (see gspice_ivar_from_skyivar
# in build_sky_defs.jl). The math lives in build_sky_defs.jl; this is the thin driver.
#
# Usage: julia --project=. scripts/prior_build/build_skyLines.jl --sample_dir=/path/to/sky_prior_disk \
#           [--chipgap_msk=/path/to/StarContChipGapMsk.h5] [--out_dir=sky_priors/]
# Author - Andrew Saydjari

import Pkg;
using Dates;
t0 = now();
t_then = t0;
using InteractiveUtils;
versioninfo();
Pkg.update("ApogeeReduction");
Pkg.instantiate();
Pkg.precompile();
t_now = now();
dt = Dates.canonicalize(Dates.CompoundPeriod(t_now - t_then));
println("Package activation took $dt"); t_then = t_now; flush(stdout);
using BLISBLAS
using Distributed, SlurmClusterManager, Suppressor, DataFrames

proj_path = dirname(Base.active_project()) * "/"
if "SLURM_NTASKS" in keys(ENV)
    using SlurmClusterManager
    addprocs(SlurmManager(), exeflags = ["--project=$proj_path"])
else
    addprocs(30, exeflags = ["--project=$proj_path"]) # change to a workers per node variable
end
t_now = now(); dt = Dates.canonicalize(Dates.CompoundPeriod(t_now - t_then));
println("Worker allocation took $dt"); t_then = t_now; flush(stdout);
println("Running Main on ", gethostname()); flush(stdout);

@everywhere begin
    using BLISBLAS
    using LinearAlgebra
    BLAS.set_num_threads(1)
    using FITSIO, HDF5, LowRankOps, EllipsisNotation, ShiftedArrays
    using Interpolations, SparseArrays, ParallelDataTransfer, AstroTime, Suppressor
    using StatsBase, ProgressMeter
end

@passobj 1 workers() proj_path
@everywhere begin
    src_dir = "$proj_path"
    include(src_dir*"src/utils.jl")
    include(src_dir*"src/gridSearch.jl")
    include(src_dir*"src/componentAndPosteriors.jl")
    include(src_dir*"src/fileNameHandling.jl")
    include(src_dir*"src/ingest.jl")
    include(src_dir*"src/lowRankPrescription.jl")
    include(src_dir*"src/marginalizeEW.jl")
    include(src_dir*"src/spectraInterpolation.jl")
    include(src_dir*"src/chi2Wrappers.jl")
    include(src_dir*"scripts/prior_build/prior_utils.jl")
    include(src_dir*"scripts/prior_build/gspice.jl")
    include(src_dir*"scripts/prior_build/build_sky_defs.jl")
end
t_now = now(); dt = Dates.canonicalize(Dates.CompoundPeriod(t_now - t_then));
println("Worker loading took $dt"); flush(stdout);
println(BLAS.get_config()); flush(stdout);

using LibGit2;
println(proj_path); flush(stdout)
git_branch, git_commit, git_clean = initalize_git(proj_path);
@passobj 1 workers() git_branch;
@passobj 1 workers() git_commit;
@passobj 1 workers() git_clean;

# E5: sample directory is a required input (was a hardcoded 2026_04_26 date path);
# the chip-gap mask and output directory are overridable the same way.
sample_dir = get_config_arg("--sample_dir"; env_key="SKY_SAMPLE_DIR")
chipgap_msk_path = get_config_arg("--chipgap_msk"; env_key="SKY_CHIPGAP_MSK",
    default="/mnt/ceph/users/sdssv/work/asaydjari/2026_04_25/StarContChipGapMsk.h5")
prior_out_dir = get_config_arg("--out_dir"; env_key="SKY_PRIOR_OUT", default="sky_priors/")
println("build_skyLines: sample_dir=$sample_dir chipgap_msk=$chipgap_msk_path out_dir=$prior_out_dir"); flush(stdout)
@passobj 1 workers() sample_dir
@passobj 1 workers() chipgap_msk_path
@passobj 1 workers() prior_out_dir

@everywhere begin
    runlist_range = 295 #1:600 #295, 245, 335, 101

    nsub_bright = 120;
    nsub_faint = 120;

    nsigma_schedule = [20, 8, 6];
    usamp_factor = 7
end

# it spends most of its time on a simple matmul ????
# M4: ENV values are Strings; BLAS.set_num_threads needs an Int (fall back to CPU count off-SLURM)
BLAS.set_num_threads(parse(Int, get(ENV, "SLURM_NTASKS", string(Sys.CPU_THREADS))));
build_skyLines(runlist_range; sample_dir=sample_dir, chipgap_msk_path=chipgap_msk_path,
    out_dir=prior_out_dir, nsub_faint=nsub_faint, nsub_bright=nsub_bright,
    nsigma_schedule=nsigma_schedule, usamp_factor=usamp_factor)
# @showprogress pmap(adjfibindx -> build_skyLines(adjfibindx; sample_dir=sample_dir,
#     chipgap_msk_path=chipgap_msk_path, out_dir=prior_out_dir, nsub_faint=nsub_faint,
#     nsub_bright=nsub_bright, nsigma_schedule=nsigma_schedule, usamp_factor=usamp_factor), 1:600)
