## This script builds the skyCont priors from a bunch of samples generated by sample_sky.jl
# Author - Andrew Saydjari

import Pkg;
using Dates;
t0 = now();
t_then = t0;
using InteractiveUtils;
versioninfo();
Pkg.update("ApogeeReduction");
Pkg.instantiate();
Pkg.precompile();
t_now = now();
dt = Dates.canonicalize(Dates.CompoundPeriod(t_now - t_then));
println("Package activation took $dt"); t_then = t_now; flush(stdout);
using BLISBLAS
using Distributed, SlurmClusterManager, Suppressor, DataFrames

proj_path = dirname(Base.active_project()) * "/"
if "SLURM_NTASKS" in keys(ENV)
    using SlurmClusterManager
    addprocs(SlurmManager(), exeflags = ["--project=$proj_path"])
else
    addprocs(30, exeflags = ["--project=$proj_path"]) # change to a workers per node variable
end
t_now = now(); dt = Dates.canonicalize(Dates.CompoundPeriod(t_now - t_then));
println("Worker allocation took $dt"); t_then = t_now; flush(stdout);
println("Running Main on ", gethostname()); flush(stdout);

@everywhere begin
    using BLISBLAS
    using LinearAlgebra
    BLAS.set_num_threads(1)
    using FITSIO, Serialization, HDF5, LowRankOps, EllipsisNotation, ShiftedArrays
    using Interpolations, SparseArrays, ParallelDataTransfer, AstroTime, Suppressor
    using StatsBase, ProgressMeter
    using ThreadPinning
end

@passobj 1 workers() proj_path
@everywhere begin
    prior_dir = "/mnt/ceph/users/sdssv/work/asaydjari/"
    src_dir = "$proj_path"
    include(src_dir*"src/utils.jl")
    include(src_dir*"src/gridSearch.jl")
    include(src_dir*"src/componentAndPosteriors.jl")
    include(src_dir*"src/fileNameHandling.jl")
    include(src_dir*"src/ingest.jl")
    include(src_dir*"src/lowRankPrescription.jl")
    include(src_dir*"src/marginalizeEW.jl")
    include(src_dir*"src/spectraInterpolation.jl")
    include(src_dir*"src/chi2Wrappers.jl")
    include(src_dir*"scripts/prior_build/prior_utils.jl")
end
t_now = now(); dt = Dates.canonicalize(Dates.CompoundPeriod(t_now - t_then));
println("Worker loading took $dt"); flush(stdout);
println(BLAS.get_config()); flush(stdout);

using LibGit2;
println(proj_path); flush(stdout)
git_branch, git_commit, git_clean = initalize_git(proj_path);
@passobj 1 workers() git_branch;
@passobj 1 workers() git_commit;
@passobj 1 workers() git_clean;

@everywhere begin
    runlist_range = 295 #1:600 #295, 245, 335, 101

    nsub = 30; # my star cont is 60... do we need to up it?

    # Prior Dictionary
    prior_dict = Dict{String,String}()

    sky_base = prior_dir*"2024_02_21/apMADGICS.jl/src/prior_build/"

    # Location of the samples
    prior_dict["skycont"] = prior_dir*"2026_04_26/sky_prior_disk/skycont_"
    prior_dict["skymsk"] = prior_dir*"2026_04_26/sky_prior_disk/skymsk_"
    prior_dict["StarContChipGapMsk"] = prior_dir*"2026_04_25/StarContChipGapMsk.h5"
end

@everywhere begin
    wavetarg = 10 .^range((4.179-125*6.0e-6),step=6.0e-6,length=8575+125) #first argument is start, revert fix to enable 1.6 compat
    minw, maxw = extrema(wavetarg)
end

@everywhere begin
    function build_skyCont(adjfibindx)
        fname = "sky_priors/APOGEE_skycont_svd_"*string(nsub)*"_f"*lpad(adjfibindx,3,"0")*".h5"
        if !isfile(fname)
            savename = prior_dict["skycont"]*lpad(adjfibindx,3,"0")*".jdat"
            skycont = deserialize(savename)

            savename = prior_dict["skymsk"]*lpad(adjfibindx,3,"0")*".jdat"
            skymsk = deserialize(savename);

            # savename = prior_dict["chebmsk_exp"]*lpad(adjfibindx,3,"0")*".jdat"
            # chebmsk_exp = deserialize(savename);
            chipgapmsk = h5open(prior_dict["StarContChipGapMsk"], "r") do f
                if adjfibindx > 300
                    read(f["lco"])
                else
                    read(f["apo"])
                end
            end

            specsum = dropdims(sum(skycont,dims=1),dims=1)
            Vred = skycont[chipgapmsk,specsum.>0];
            # weights = ones(size(Vred,2));
            # Vred .*= reshape(weights,1,:);
            nsamp = size(Vred,2)
            # norm_weights = weights'*weights
            Csky = Vred*Vred'
            # Csky./=norm_weights
            Csky./=nsamp

            SF = svd(Csky);
            EVEC = zeros(length(wavetarg),size(SF.U,2))
            EVEC[chipgapmsk,:].=SF.U;

            dirName = splitdir(fname)[1]
            if !ispath(dirName)
                mkpath(dirName)
            end
            h5write(fname,"Vmat",EVEC[:,1:nsub]*Diagonal(sqrt.(SF.S[1:nsub])))
            h5write(fname,"λv",SF.S[1:nsub])
        end
    end
end

# observing, it spent a most of the time before entering the multithreaded SVD. Why?
BLAS.set_num_threads(ENV["SLURM_NTASKS"]); build_skyCont(runlist_range)
# @showprogress pmap(build_skyCont,1:600)